apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    torque-cluster-id: 7cc003b7-873c-4966-a286-6cb44e42e57a
  name: torque-agent-sa-1f58b4
  namespace: ophirus-agent

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    torque-cluster-id: 7cc003b7-873c-4966-a286-6cb44e42e57a
  name: torque-sidecar-sa-1f58b4
  namespace: ophirus-sandboxes

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    torque-cluster-id: 7cc003b7-873c-4966-a286-6cb44e42e57a
  name: torque-cr-r-1f58b4
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    torque-cluster-id: 7cc003b7-873c-4966-a286-6cb44e42e57a
  name: torque-nr-r-1f58b4
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ''
  - events.k8s.io
  resources:
  - events
  verbs:
  - list
  - get
- apiGroups:
  - ''
  resources:
  - pods
  - pods/log
  - persistentvolumeclaims
  - services
  - configmaps
  - endpoints
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    torque-cluster-id: 7cc003b7-873c-4966-a286-6cb44e42e57a
  name: torque-cr-b-1f58b4
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: torque-cr-r-1f58b4
subjects:
- kind: ServiceAccount
  name: torque-agent-sa-1f58b4
  namespace: ophirus-agent

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    torque-cluster-id: 7cc003b7-873c-4966-a286-6cb44e42e57a
  name: torque-nr-b-1f58b4
  namespace: ophirus-sandboxes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: torque-nr-r-1f58b4
subjects:
- kind: ServiceAccount
  name: torque-agent-sa-1f58b4
  namespace: ophirus-agent
- kind: ServiceAccount
  name: torque-sidecar-sa-1f58b4
  namespace: ophirus-sandboxes

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    torque-cluster-id: 7cc003b7-873c-4966-a286-6cb44e42e57a
  name: torque-agent-s-1f58b4
  namespace: ophirus-agent
stringData:
  cluster-token: 783fe580-5b6a-43c9-9419-3749e1ab54c7
  logzio-token: ruNbNOjJuvBwUXeToQttHqKClRqbuCkg

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    torque-cluster-id: 7cc003b7-873c-4966-a286-6cb44e42e57a
  name: torque-agent-rs-1f58b4
  namespace: ophirus-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      torque-cluster-id: 7cc003b7-873c-4966-a286-6cb44e42e57a
      app: torque-agent
  template:
    metadata:
      labels:
        torque-cluster-id: 7cc003b7-873c-4966-a286-6cb44e42e57a
        app: torque-agent
    spec:
      containers:
      - env:
        - name: AgentSettings__LogzioToken
          valueFrom:
            secretKeyRef:
              key: logzio-token
              name: torque-agent-s-1f58b4
        - name: AgentSettings__ClusterToken
          valueFrom:
            secretKeyRef:
              key: cluster-token
              name: torque-agent-s-1f58b4
        - name: AgentSettings__ClusterId
          value: 7cc003b7-873c-4966-a286-6cb44e42e57a
        - name: AgentSettings__ServerUrl
          value: https://portal.qtorque.io/hub/agent
        - name: AgentSettings__RegistryImage
          value: quali/kubernetes-agent:1.0.1225
        image: quali/kubernetes-agent:1.0.1225
        imagePullPolicy: IfNotPresent
        name: torque-agent-container
      serviceAccountName: torque-agent-sa-1f58b4
