version: '3.8'
services:
  guacd:
    image: guacamole/guacd
    ports:
      - 4822:4822
    environment:
      - GUACD_LOG_LEVEL=debug 
  guacamole:
    image: guacamole/guacamole
    ports:
      - 8080:8080
    environment:
      - GUACD_HOSTNAME=guacd
      - GUACD_PORT=4822